#!/bin/bash
#
# This script runs all of the ILOC files in the current directory (./*.i)
# through a register allocator; runs the resulting code through the ILOC
# simulator; checks the output values against the specifications provided
# in the comments of the original ILOC file; and reports both correctness
# and the number of cycles required to execute the allocated code.
#
# usage: AllocAndRunAll <directory> <allocator> <k>
#
# where k is the number of registers to be passed to the allocator, default 5
# 
#
DIR=$(pwd)
CHECK=/users/sfogarty/tools_csci3334/p2/tools/CheckResults
SIM=/users/sfogarty/tools_csci3334/p1/sim
RUN=/users/sfogarty/tools_csci3334/p1/scripts/ReadOne
LOG=~/AllocTest.log
if [ $# -lt 2 ]; then
    echo "Usage: testReaderIloc <reader> <directory> "
    echo "Where <reader> points to your allocator,"
    echo '  <directory> points to a directory of test files.'
    exit
fi
ALLOC=$1
DIR=$2
echo "Reading and Testing ILOC Files"
echo "in $DIR"
echo " "
echo "-----" >&$LOG
FLIST=$(ls $DIR/*.i)
#
for f in $(ls $DIR/*.i); do
    $RUN $f $ALLOC $SIM >> $LOG
    echo "-----" >> $LOG
done
#

$CHECK $LOG
rm /tmp/test.i
